CREATE TABLE Companies (
  Id VARCHAR(255) PRIMARY KEY NOT NULL,
  Cnpj VARCHAR(20) NOT NULL,
  Name VARCHAR(60) NOT NULL,
  SocialReason VARCHAR(60) NOT NULL,
  Email VARCHAR(30) NOT NULL,
  Phone VARCHAR(20) NOT NULL,
  Information VARCHAR(255) NOT NULL,
  ShopmanId VARCHAR(255) NOT NULL
);

CREATE TABLE Users (
  Id VARCHAR(255) PRIMARY KEY NOT NULL,
  Name VARCHAR(30) NOT NULL,
  Role VARCHAR(10) NOT NULL,
  Email VARCHAR(30) NOT NULL,
  Password VARCHAR(255),
  Phone1 VARCHAR(20) NOT NULL,
  Phone2 VARCHAR(20)
);
